version: '3.9'
services:
  nest-api:
    container_name: Nest API
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/app
      - /home/app/node_modules
    command: yarn staer:dev
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    restart: unless-stopped
    links:
      - pg
    depends_on:
      - pg
    networks:
      - db-network

  pg:
    image: postgres:14-alpine
    restart: always
    container_name: postgres
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - db-network
    volumes:
      - .docker/postgres:/postgres

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '5000:80'
networks:
  db-network:
    driver: bridge
