@baseUrl=http://localhost:8000/api

### Coffees ###

# @name Get all coffees
GET {{baseUrl}}/coffees?limit=2&offset=10
Content-Type: application/json

###

# @name Get coffee by id
GET  {{baseUrl}}/coffees/1
Content-Type: application/json

###

# @name Create coffee
POST {{baseUrl}}/coffees
Content-Type: application/json

{
	"name": "Cappuccino",
	"brands":"Starbucks",
	"flavors": ["Milk", "Chocolate"]
}


###

# @name Update coffee by id
PUT {{baseUrl}}/coffees/1
Content-Type: application/json

###

# @name Delete coffee by id

DELETE {{baseUrl}}/coffees/1
Content-Type: application/json
