# Variables
@baseUrl=http://localhost:8000/api
@resouceName=posts

@postId=123

@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5taHVuZy5kZXZAZ21haWwuY29tIiwidXNlcklkIjoxLCJpc1ZlcmlmaWVkIjp0cnVlLCJyb2xlIjoidXNlciIsImlhdCI6MTY3Nzc0MjAwOCwiZXhwIjoxNjc3NzQ1NjA4fQ.8AP8FgXsQpjONIIA_9_rQVZ6F8EJJxjBcw56pADQq6A


# @name Get all posts of user
GET {{baseUrl}}/{{resouceName}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

# @name Get post by id
GET {{baseUrl}}/{{resouceName}}/{{postId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

# @name Create post
POST {{baseUrl}}/{{resouceName}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "example",
  "content": "This is content of this post",
  "slug": ":this-is-a-post"
}

###

# @name Update post
PATCH {{baseUrl}}/{{resouceName}}/{{postId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "example",
  "content": "This is content of this post",
  "slug": ":this-is-a-post"
}

###