# Variables
@baseUrl=http://localhost:8000/api
@resouceName=posts

@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5taHVuZy5kZXZAZ21haWwuY29tIiwidXNlcklkIjoxLCJpc1ZlcmlmaWVkIjpmYWxzZSwicm9sZSI6InVzZXIiLCJpYXQiOjE2NzMxODkwNzksImV4cCI6MTY3MzE5MjY3OX0.2fCMfTeyzZPzrpRMy6zRpf3K1uPZYRTPQnROYaIg0U4

# @name Get all users
GET {{baseUrl}}/{{resouceName}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

# @name Get user by id
GET {{baseUrl}}/{{resouceName}}/123 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

# @name Create user
POST {{baseUrl}}/{{resouceName}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
		"email": "nmhung.dev@gmail.com"
}

###
