# Variables
@baseUrl=http://localhost:8000/api
@accessToken=

### Users ###

# @name Get all users
GET {{baseUrl}}/users
Content-Type: application/json

###

# @name Get user by id
GET {{baseUrl}}/users/123
Content-Type: application/json

###

# @name Create user
POST {{baseUrl}}/users
Content-Type: application/json
{
	"email": "example@example.com",
	"password": "12345678",
}

###
